import { NewsArticlePlaceholder } from "@/types/news";

export const PLACEHOLDER_ARTICLES: NewsArticlePlaceholder[] = [
  {
    id: "lead-story-1",
    title: "Global Climate Summit Concludes With Binding Pact on Industrial Methane Emissions",
    excerpt: "Delegates from over 80 nations have finalized a landmark treaty establishing strict regulatory caps on energy-sector emissions, signaling a renewed momentum for multilateral environmental policy.",
    slug: "global-climate-summit-industrial-methane-pact",
    primaryCategory: "world",
    additionalCategories: ["technology"],
    tags: ["Climate Change", "Diplomacy", "Energy", "Policy"],
    author: {
      name: "Eleanor Vance",
      role: "Senior Diplomatic Correspondent",
    },
    publishedAt: "2026-09-15T18:30:00Z",
    readTime: "5 min read",
    imageUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1200&auto=format&fit=crop",
    imageCaption: "Delegates gather during the plenary session of the international conference hall.",
    isFeatured: true,
  },
  {
    id: "tech-story-1",
    title: "Autonomous Compute Clusters Transition from Research Labs to Grid Optimization",
    excerpt: "New computational frameworks are enabling power utilities to dynamically balance renewable distribution with predictive machine intelligence, cutting transmission loss across regional networks.",
    slug: "autonomous-compute-grid-optimization",
    primaryCategory: "technology",
    tags: ["Artificial Intelligence", "Clean Energy", "Computing"],
    author: {
      name: "Marcus Thorne",
      role: "Technology Editor",
    },
    publishedAt: "2026-09-15T16:45:00Z",
    readTime: "4 min read",
    imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=800&auto=format&fit=crop",
    imageCaption: "High-density server architecture in a decentralized energy monitoring facility.",
    isTrending: true,
  },
  {
    id: "us-story-1",
    title: "Federal Reserve Holds Benchmark Rates Steady as Labor Metrics Signal Balanced Growth",
    excerpt: "The central bank signaled a measured approach to monetary policy, noting steady wage gains and subdued inflationary pressures across manufacturing and service sectors.",
    slug: "federal-reserve-benchmark-rates-steady",
    primaryCategory: "us",
    tags: ["Economy", "Federal Reserve", "Banking"],
    author: {
      name: "Sarah Jenkins",
      role: "Economics Analyst",
    },
    publishedAt: "2026-09-15T15:20:00Z",
    readTime: "3 min read",
    imageUrl: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?q=80&w=800&auto=format&fit=crop",
    imageCaption: "The Federal Reserve building in Washington, D.C.",
  },
  {
    id: "uk-story-1",
    title: "Parliamentary Committee Unveils Comprehensive Framework for National Rail Modernization",
    excerpt: "Cross-party legislators have put forward a 15-year blueprint focusing on electrification, high-capacity intercity links, and unified regional fare structures.",
    slug: "parliamentary-committee-rail-modernization",
    primaryCategory: "uk",
    tags: ["Infrastructure", "Transport", "Parliament"],
    author: {
      name: "Arthur Pendelton",
      role: "UK Affairs Correspondent",
    },
    publishedAt: "2026-09-15T14:10:00Z",
    readTime: "4 min read",
    imageUrl: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?q=80&w=800&auto=format&fit=crop",
    imageCaption: "Passenger rail terminal in central London during morning service.",
  },
  {
    id: "sports-story-1",
    title: "International Athletics Federation Approves Revamped Diamond League Calendar for 2027",
    excerpt: "The redesigned schedule introduces regional qualifying sprints and expanded prize distribution aimed at elevating global spectator engagement.",
    slug: "athletics-federation-revamped-calendar-2027",
    primaryCategory: "sports",
    tags: ["Track and Field", "Athletics", "Championships"],
    author: {
      name: "David Sterling",
      role: "Sports Desk",
    },
    publishedAt: "2026-09-15T12:00:00Z",
    readTime: "3 min read",
    imageUrl: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?q=80&w=800&auto=format&fit=crop",
    imageCaption: "Sprinters prepare at the starting blocks in the national stadium.",
  },
  {
    id: "ent-story-1",
    title: "Venice Biennale Architecture Pavilion Explores Communal Habitats in Post-Dense Cities",
    excerpt: "Curators showcase how modular timber structures and decentralized micro-parks are redefining urban revitalization across five continents.",
    slug: "venice-biennale-communal-habitats-post-dense-cities",
    primaryCategory: "entertainment",
    tags: ["Architecture", "Design", "Culture", "Arts"],
    author: {
      name: "Clara Moreau",
      role: "Arts & Culture Critic",
    },
    publishedAt: "2026-09-15T11:15:00Z",
    readTime: "5 min read",
    imageUrl: "https://images.unsplash.com/photo-1508997449629-303059a039c0?q=80&w=800&auto=format&fit=crop",
    imageCaption: "Exhibition hall presenting sustainable urban scale models.",
  },
  {
    id: "tech-story-2",
    title: "Deep-Sea Telemetry Arrays Deploy Solid-State Optical Sensors for Seismology",
    excerpt: "Oceanographic institutes establish a new baseline for early detection of seismic activity using subsea fiber cables repurposed as wide-area acoustic sensors.",
    slug: "deep-sea-telemetry-optical-sensors-seismology",
    primaryCategory: "technology",
    additionalCategories: ["world"],
    tags: ["Geophysics", "Oceanography", "Hardware"],
    author: {
      name: "Marcus Thorne",
      role: "Technology Editor",
    },
    publishedAt: "2026-09-15T09:30:00Z",
    readTime: "4 min read",
    imageUrl: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=800&auto=format&fit=crop",
    imageCaption: "Marine research vessel deploying oceanic monitoring instrument packages.",
    isTrending: true,
  },
  {
    id: "world-story-2",
    title: "Nordic Coalition Signs Pact to Standardize Cross-Border Green Energy Grids",
    excerpt: "Sweden, Norway, Denmark, and Finland agree to synchronize regulatory standards, clearing hurdles for offshore wind integration into regional power markets.",
    slug: "nordic-coalition-cross-border-green-energy-pact",
    primaryCategory: "world",
    tags: ["Renewables", "Europe", "Energy"],
    author: {
      name: "Eleanor Vance",
      role: "Senior Diplomatic Correspondent",
    },
    publishedAt: "2026-09-15T08:00:00Z",
    readTime: "3 min read",
    imageUrl: "https://images.unsplash.com/photo-1466611653911-95081537e5b7?q=80&w=800&auto=format&fit=crop",
    imageCaption: "Wind turbine installations along the coastal Baltic archipelago.",
  },
];
